### ISSUE TITLE
Practica-5_Irving

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-20-equipo-de-irving#3]
[Reporte de Practica5.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-20-equipo-de-irving/files/9630729/Reporte.de.Practica5.pdf)

**Comment by magaly1311** [comment]
calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
